# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Upload Android App To Firebase Distribution"
    lane :distribute_android_app do
      Dir.chdir "../.." do
            sh("sh", "increase_build_number.sh")
            sh("flutter", "packages", "get")
            sh("flutter", "clean")
            sh("flutter", "build", "apk", "--release")
          end
      copy_artifacts(
            artifacts: ['../build/app/outputs/flutter-apk/app-release.apk'],
            target_path: './build/apk'
          )
      firebase_app_distribution(
            app: "1:130967009682:android:3140d0bcb430273672e94b",
            testers: "lamdt.nws@gmail.com",
            apk_path: "./build/apk/app-release.apk",
            android_artifact_type: "APK",
            service_credentials_file: "../android/key/firebase-distribution-key.json",
            groups: "dev"
          )
      # sh "your_script.sh"
      # You can also use other beta testing services here
    end

  desc "Upload Android App To Play Store"
      lane :upload_app do
        Dir.chdir "../.." do
              sh("sh", "increase_build_number.sh")
              sh("flutter", "packages", "get")
              sh("flutter", "clean")
              sh("flutter", "build", "appbundle", "--release")
            end
        copy_artifacts(
              artifacts: ['../build/app/outputs/bundle/release/app-release.aab'],
              target_path: './build/aab'
            )
        Dir.chdir "../.." do
           sh("make", "upload_app_android")
           end
      end
end
